aws_gate/cli.py, aws_gate/utils.py
It solves Issue https://github.com/xen0l/aws-gate/issues/7
=> Remove hardcoded defaults

aws_gate/query.py, test/unit/test_query.py
Fixes #12. Also increases performance on queries by tag.
=> Introduce option to query by name 

CHANGELOG.md, aws_gate/query.py
=> aws-gate can open session to terminated instances

aws_gate/bootstrap.py, aws_gate/decorators.py, test/unit/test_bootstrap.py
=> bootstrap not working when ~/.aws-gate is missing

docs/changelog.md, docs/command-line.md, docs/configuration.md, docs/development.md, docs/index.md, docs/license.md, docs/quickstart.md, mkdocs.yml
=> Add initial documentation

CHANGELOG.md, aws_gate/bootstrap.py, aws_gate/constants.py, requirements/requirements.txt, test/unit/test_bootstrap.py
=> Add support for downloading Linux plugin

aws_gate/cli.py, tests/unit/test_cli.py
=> Use aws-vault profile when available

CHANGELOG.md, README.md, aws_gate/cli.py, aws_gate/ssh.py, docs/command-line.md, docs/index.md, docs/quickstart.md, tests/unit/test_cli.py, tests/unit/test_ssh.py
aws-gate should support opening SSH sessions directly. This addresses #78
=> Add ssh subcommand

completions/bash/aws-gate
=> Add bash completion

.coveragerc, tests/unit/test_cli.py, tests/unit/test_config.py
Irrelevant milestone, but for sake of completness..
=> Increase test coverage to 100%

aws_gate/query.py, tests/unit/test_query.py
=> Querying instances by autoscaling group tag is broken

README.md, aws_gate/query.py, tests/unit/test_query.py
=> Support querying instances by autoscaling group name

aws_gate/query.py, tests/unit/placebo/test_query_instance_by_tag_parsing/ec2.DescribeInstances_1.json, tests/unit/test_query.py
=> Fix querying instance by autoscaling group

aws_gate/utils.py, tests/unit/test_utils.py
=> Extend user agent with aws-gate version information

CHANGELOG.md, aws_gate/list.py, aws_gate/utils.py
=> Improve listing performance

aws_gate/utils.py, tests/unit/test_utils.py
=> mfa-support

docs/configuration.md
Fix misspelling and typos in the documentation
=> Fix Doc typos

aws_gate/utils.py, tests/unit/test_utils.py
=> Fix env=None introduced in #572

.coveragerc, .pylintrc, aws_gate/cli.py, aws_gate/ssh.py, tests/unit/test_ssh.py
This PR expands support for all supported port forwarding types in `aws-gate ssh`
=> Support dynamic and remote port forwarding in aws-gate ssh

.github/workflows/python-package.yml, .pylintrc, aws_gate/bootstrap.py, aws_gate/cli.py, aws_gate/config.py, aws_gate/decorators.py, aws_gate/exec.py, aws_gate/list.py, aws_gate/query.py, aws_gate/session.py, aws_gate/ssh.py, aws_gate/ssh_common.py, aws_gate/ssh_config.py, aws_gate/ssh_proxy.py, aws_gate/utils.py, tests/run.py, tests/unit/test_bootstrap.py, tests/unit/test_cli.py, tests/unit/test_config.py, tests/unit/test_list.py, tests/unit/test_ssh_config.py, tests/unit/test_utils.py
This PR:
* drops Python 3.6
* converts code to use f-strings
* make code pylint-clean
=> Maintenance updates

aws_gate/list.py
=> fix(list-instances): add instance only with the online pingstatus

aws_gate/list.py, tests/unit/placebo/test_list/ssm.DescribeInstanceInformation_1.json
=> Add test case for pingstatus check
